using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.AI;

public class Monster : MonoBehaviour
{
    // Start is called before the first frame update
    void Start () {
        // Navigate to Castle
        GameObject castle = GameObject.Find("Castle");
        if (castle)
            GetComponent<NavMeshAgent>().destination = castle.transform.position;
    }
    
    void OnTriggerEnter(Collider co) {
        // If castle then deal Damage
        if (co.name == "Castle") {
            co.GetComponentInChildren<Health>().decrease();
            Destroy(gameObject);
        }
    }
}
